import { chromium } from '@playwright/test';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto('http://localhost:5173');
await page.waitForTimeout(1200);
await page.click('button:has-text("Entrar")');
await page.waitForTimeout(1200);
const body = await page.textContent('body');
['Os Meus Espaços','URGENTE','Os Seus Espaços','Votação a Decorrer','Novos na Rede','Adicionar','Quotas em dia'].forEach(c => console.log(`${c}: ${body.includes(c)}`));
await page.click('button:has-text("Eventos")');
await page.waitForTimeout(800);
const bodyEv = await page.textContent('body');
console.log('Calendar Julho 2026:', bodyEv.includes('Julho 2026'));
console.log('Confirmar presença:', bodyEv.includes('Confirmar presença'));
await page.click('button:has-text("Mensagens")');
await page.waitForTimeout(800);
const bodyMsg = await page.textContent('body');
console.log('Tabs Conversas/Contactos:', bodyMsg.includes('Conversas') && bodyMsg.includes('Contactos'));
await page.click('button:has-text("Directório")');
await page.waitForTimeout(800);
const bodyDir = await page.textContent('body');
console.log('O Meu Directório col:', bodyDir.includes('O Meu Directório'));
await browser.close();
console.log('ALL DONE');
